#!/bin/bash
#
# PycketJS

CWD=`pwd`
SCRIPT=`realpath $0`
SCRIPTPATH=`dirname $SCRIPT`
EMCC_SRC=$SCRIPTPATH/emscripten/
EMCC_TMP_FILE="pycket_fs_init.js"
BUILD_FLAGS=""
PYPY="pypy"

function pycketjs_setup () {
    mkdir racket
    cp -a /usr/share/racket/collects racket
}

function pycketjs_clean () {
    rm -rf build/ clean/ $EMCC_TMP_FILE *.rkt.json
}

function pycketjs_build_modules() {
    racket --collects $CWD/racket/collects $SCRIPTPATH/bundle.rkt $BUILD_FLAGS build.rktl
}

function pycketjs_emcc_package() {
    mv build pycketjs
    python $EMCC_SRC/tools/file_packager.py pycket.js --embed `find pycketjs/ -type f` --lz4 --js-output-file=$EMCC_TMP_FILE || true
    mv pycketjs build
}

function pycketjs_bundle() {
    cat pycket_fs_init.js $SCRIPTPATH/pycket.js > pycket.js
}

function pycketjs_build () {
    pycketjs_build_modules
    pycketjs_emcc_package
    pycketjs_bundle
}

function pycketvm_build() {
    OLD_DIR=`pwd`
    cd $SCRIPTPATH

    mkdir -p $SCRIPTPATH/pycketvm
    cd pycketvm

    git clone https://github.com/samth/pycket.git || echo "Pycket already cloned"
    cd pycket

    docker pull rfkelly/pypyjs-build
    cp $SCRIPTPATH/Dockerfile .
    docker build -t vishesh/pycketjs .
    DOCKER_CMD="docker run -it -v $SCRIPTPATH/pycketvm/pycket:/work -w /work vishesh/pycketjs"
    
    hg clone https://vishesh@bitbucket.org/vishesh/pypy || echo "Pypy already cloned"
    $DOCKER_CMD $PYPY ./pypy/rpython/bin/rpython --backend=js targetpycket.py
    mv pycket-js-js-nojit $SCRIPTPATH/pycket.js

    cd $OLD_DIR
}

set -e

case "$1" in
    "setup" )
	pycketjs_setup
	;;
    "clean" )
	pycketjs_clean
	;;
    "build" )
	pycketjs_build
	;;
    "quickbuild" )
        BUILD_FLAGS="--ignore-collects"
        pycketjs_build
        ;;
    "emcc-package" )
	pycketjs_emcc_package
	;;
    "bundle" )
	pycketjs_bundle
	;;
    "cleanbuild" )
        pycketjs_clean
        pycketjs_build
	;;
    "pycketvm-build" )
        pycketvm_build
        ;;
    * ) echo "Invalid arguments.";;
esac
